apiVersion: v1
kind: Service
metadata:
  name: myapp-cluster-service

spec:
  type: ClusterIP
  ports:

    - targetPort: 80 # if this field doesn't, it will assume the value is same as port
      port: 80  # this field is mandatory

      # note target port is the port where service exposed

  selector:
    app: myapp
    type: front-end
