apiVersion: apps/v1 
kind: Deployment
metadata:
  name: myapp-rc
  labels:
    app: myapp
    type: asdfhjkl
spec:
  template:
    metadata: # dictionary for pods
      name: nginx
      labels: # dictionary
        app: myapp
        tier: router
        tag: fuckthis
    spec:
      containers:
      - name: nginx
        image: nginx

  replicas: 5
  selector:
    matchLabels:
      app: myapp

