apiVersion: v1
kind: Pod
metadata: # dictionary
  name: nginx
  labels: # dictionary
    app: nginx
    tier: router
    tag: fuckthis
spec:
  containers:  # list of objects (dictionaries)
  - name: nginx
    image: nginx

  # one could add more container in this
  # but it will be multiple container in same pod