apiVersion: v1
kind: Service
metadata:
  name: myapp-node-service

spec:
  type: NodePort
  ports:
    # note that this is an array
    # that means, there could be multiple port mappings
    # in one service

    - targetPort: 80 # if this field doesn't, it will assume the value is same as port
      port: 80  # this field is mandatory
      nodePort: 30008 # if this field doesn't exists, it will automatically allocated a port
      # within 30008 to 30767 (of course it will allocate a free port)

  # there might be thousands of pod that expose port 80
  # so we need selector to filter pods by labels to determine
  # which pod we are connecting to.
  selector:
    app: myapp
    type: front-end


# What if we have a replicaset? meaning 3 pods with same label?
# kubernetes does this for us, it uses a random algorithm call Roulette wheel algorithm
# to distribute connections seperately to each pods.